### ISSUE TITLE
Playing with fire

### ISSUE THREAD

**Issue by AdamVVG** [emcf/HLVM#10]
Hello,

While I think that this is a super cool and interesting repo, don't you think this is playing with fire a little bit? Giving GPT the ability to execute code without first seeing the code feels like it could have very bad, unexpected consequences.

Please be careful!

**Comment by debakarr** [comment]
Lately I see lots of tools getting created using GPT, but all of them lack security.

**Comment by cschladetsch** [comment]
Run it in a VM, and/or take your chances.

**Comment by emcf** [comment]
Please read the README.
