### ISSUE TITLE
How is it different from the Codex-CLI??

### ISSUE THREAD

**Issue by uuc110** [emcf/HLVM#13]
And When i'm using my OpenAI API Key its shows Limit reacher? then how can those user who reacher thier limit use such open source tool

**Comment by emcf** [comment]
AFAIK, Codex-CLI does not allow for the wide functionality and API compatibility that Python scripts offer, nor does it debug/install on its own.

**Comment by uuc110** [comment]
> AFAIK, Codex-CLI does not allow for the wide functionality and API compatibility that Python scripts offer, nor does it debug/install on its own.

And What about those limit reacher users? Can i do something or is there something to re-new my limit (I mean, does OpenAi renew the limit every month or something which i don't know)
