### ISSUE TITLE
need to purchase a plan?

### ISSUE THREAD

**Issue by zeydabadi** [emcf/HLVM#14]
Do we need to purchase a plan from openai?

I get this error: `openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.`

**Comment by intimidavid** [comment]
You need to give your billing details to OpenAI. You can track your usage on the website. You would have to use it a lot for it to cost more than $0.50 or so for the day.

**Comment by kraibse** [comment]
I was wondering about that too. Where can I configure my desired LLM?

**Comment by emcf** [comment]
You can visit [here](https://openai.com/pricing) to get set up with OpenAI's API :)

**Comment by MZeydabadi** [comment]
They advise to not share the API key
