### ISSUE TITLE
Got the following error while trying to run, not a Python expert myself.

### ISSUE THREAD

**Issue by JoseWalker** [emcf/HLVM#19]
File "engshell.py", line 24
    print(engshell_PREVIX(), end="")
                                ^
SyntaxError: invalid syntax

**Comment by emcf** [comment]
> File "engshell.py", line 24 print(engshell_PREVIX(), end="") ^ SyntaxError: invalid syntax

Hi Jose, it looks like that line should be indented, so maybe you accidentally deleted the indent, and thus doing `git fetch origin` then `git pull` will fix it.

If that doesn't do the trick would you mind doing `python ––version` in your console so I can see what python you're running?
Also, have you ran `pip install -r requirements.txt`?
