### ISSUE TITLE
error running python engshell.py

### ISSUE THREAD

**Issue by bcullman** [emcf/HLVM#23]
zsh ❯ python engshell.py
Traceback (most recent call last):
  File "/home/me/engshell/engshell.py", line 6, in <module>
    from prompts import *
  File "/home/me/engshell/prompts.py", line 5, in <module>
    USERNAME = os.getlogin()
FileNotFoundError: [Errno 2] No such file or directory

This is Ubuntu (WSL)

**Comment by CuongTranXuan** [comment]
it is probably an issue of WSL itself, since someone has already mentioned it in here: https://unix.stackexchange.com/questions/518396/getlogin-not-working-on-windows-subsystem-for-linux-wsl

**Comment by emcf** [comment]
solved with #20
