### ISSUE TITLE
Feature request : Option to use poe api 

### ISSUE THREAD

**Issue by wrobm2** [emcf/HLVM#25]
https://github.com/ading2210/poe-api

its free and would be really nice to have as an alternative to the openai api

**Comment by wrobm2** [comment]
Huggingface api would also work as an alternative

**Comment by wrobm2** [comment]
https://github.com/xtekky/gpt4free

**Comment by emcf** [comment]
Thanks for making the issue @wrobm2, looking into this

**Comment by emcf** [comment]
Closing this issue as the use of these wrappers is not legal in my country. The code is under MIT license so feel free to modify and redistribute as you like.
