### ISSUE TITLE
Not working but not telling any errors 

### ISSUE THREAD

**Issue by alexbespik** [emcf/HLVM#6]
![image](https://user-images.githubusercontent.com/122635924/229930989-c1261ea3-19ff-4ceb-bf64-21687cb3a717.png)

**Comment by alexbespik** [comment]
![image](https://user-images.githubusercontent.com/122635924/229931609-568a461b-950d-4e51-99f6-496000dc1274.png)
another variant

**Comment by emcf** [comment]
> ![image](https://user-images.githubusercontent.com/122635924/229930989-c1261ea3-19ff-4ceb-bf64-21687cb3a717.png)

Looks like it worked fine in this case.


> ![image](https://user-images.githubusercontent.com/122635924/229931609-568a461b-950d-4e51-99f6-496000dc1274.png) another variant

What is your expected output for the command "Why". It's not obvious to me that this should map to a specific operation on the computer.

That being said, we are definitely not prompting well enough to ensure that the LLM outputs only python code and nothing else. Suggestions are welcome.
